on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: arcdemo232.azurecr.io
        username: ${{ secrets.acr_arcdemo232_username }}
        password: ${{ secrets.acr_arcdemo232_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t arcdemo232.azurecr.io/akslabtest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push arcdemo232.azurecr.io/akslabtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akslabtest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akslabtest | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akslabtest`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akslabtest
        container-registry-url: arcdemo232.azurecr.io
        container-registry-username: ${{ secrets.acr_arcdemo232_username }}
        container-registry-password: ${{ secrets.acr_arcdemo232_password }}
        secret-name: akslabtestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akslabtest
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          arcdemo232.azurecr.io/akslabtest:${{ github.sha }}
        imagepullsecrets: |
          akslabtestdockerauth
